import CustomEvents from "./MouseEventHandler.js";
import draw from "./draw.js";
import * as API from "./API.js";
import ZoomHandler from "./Zoom.js";
function init() {
    const viewport = document.createElement("div");
    viewport.setAttribute("id", "viewport");
    viewport.style.width = "100000px";
    viewport.style.height = "100000px";
    viewport.setAttribute("transform", "matrix(1, 0, 0, 1, -50000, -50000)");
    const svg_root = document.createElementNS("http://www.w3.org/2000/svg", "svg");
    svg_root.setAttribute("id", "svg-root");
    svg_root.setAttribute("width", "100000px");
    svg_root.setAttribute("height", "100000px");
    svg_root.style.position = "absolute";
    svg_root.style.zIndex = "10";
    svg_root.style.pointerEvents = "none";
    const svg_viewport = document.createElementNS("http://www.w3.org/2000/svg", "g");
    svg_viewport.setAttribute("id", "svg-viewport");
    svg_viewport.setAttribute("width", "100000px");
    svg_viewport.setAttribute("height", "100000px");
    svg_viewport.setAttribute("transform", "matrix(1, 0, 0, 1, -50000, -50000)");
    svg_viewport.style.position = "absolute";
    svg_viewport.style.zIndex = "1";
    svg_viewport.style.pointerEvents = "none";
    const lineContainer = document.createElementNS("http://www.w3.org/2000/svg", "g");
    ;
    lineContainer.setAttribute("id", "lines");
    lineContainer.setAttribute("width", "100%");
    lineContainer.setAttribute("height", "100%");
    lineContainer.setAttribute("tabindex", "-1");
    lineContainer.style.position = "absolute";
    lineContainer.style.zIndex = "2";
    lineContainer.style.pointerEvents = "none";
    lineContainer.style.width = "100%";
    lineContainer.style.height = "100%";
    const lineLabelContainer = document.createElementNS("http://www.w3.org/2000/svg", "text");
    lineLabelContainer.setAttribute("id", "line-labels");
    lineLabelContainer.setAttribute("dy", "-20");
    const overlayContainer = document.createElementNS("http://www.w3.org/2000/svg", "g");
    overlayContainer.setAttribute("id", "overlay");
    overlayContainer.setAttribute("min-width", "100vw");
    overlayContainer.setAttribute("min-height", "100vh");
    overlayContainer.setAttribute("fill", "none");
    overlayContainer.style.position = "absolute";
    overlayContainer.style.zIndex = "5";
    overlayContainer.style.pointerEvents = "none";
    overlayContainer.style.width = "100%";
    overlayContainer.style.height = "100%";
    const pointerContainer = document.createElementNS("http://www.w3.org/2000/svg", "g");
    pointerContainer.setAttribute("transform", "matrix(1, 0, 0, 1, 50000, 50000)");
    pointerContainer.setAttribute("id", "pointer-layer");
    pointerContainer.setAttribute("min-width", "100vw");
    pointerContainer.setAttribute("min-height", "100vh");
    pointerContainer.setAttribute("fill", "none");
    pointerContainer.style.position = "absolute";
    pointerContainer.style.zIndex = "10";
    pointerContainer.style.pointerEvents = "none";
    pointerContainer.style.width = "100%";
    pointerContainer.style.height = "100%";
    const canvas = document.createElement("div");
    canvas.setAttribute("id", "canvas");
    lineContainer.appendChild(lineLabelContainer);
    svg_viewport.appendChild(lineContainer);
    svg_viewport.appendChild(overlayContainer);
    svg_viewport.appendChild(pointerContainer);
    svg_root.appendChild(svg_viewport);
    document.body.appendChild(svg_root);
    viewport.appendChild(canvas);
    document.body.appendChild(viewport);
    let events = new CustomEvents();
    draw();
    if (window.visualViewport) {
        window.visualViewport.onresize = () => {
            draw();
        };
    }
    API.notify("canvas-ready", { value: true });
}
init();
// @ts-ignore
window.API = API;
const zoomHandler = new ZoomHandler();
export default zoomHandler;
